pipeline {
    agent any

    environment {
        IMAGE_NAME = "inventory-service"
        DOCKER_HUB_REPO = "aminebd14"
        DOCKER_USERNAME = "aminebd14"
        DOCKER_PASSWORD = "dckr_pat_JldbWHItHP63m3HMjBXFJGyS9Tg"
        TESTCONTAINERS_HOST_OVERRIDE = "host.docker.internal"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                dir('inventory-service') {
                    sh "docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME:latest ."
                }
            }
        }

        stage('Deploy to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-creds',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
                        docker logout
                    '''
                }
            }
        }
    }
}
